# jdk 层
FROM arm64v8/ubuntu:20.04 as base-jdk
MAINTAINER chenjh "842761733@qq.com"
# 内置一些常用的中文字体，避免普遍性乱码
COPY fonts/* /usr/share/fonts/chinese/
RUN apt-get clean && apt-get update &&\
	# sed -i 's/http:\/\/archive.ubuntu.com/https:\/\/mirrors.aliyun.com/g' /etc/apt/sources.list &&\
	# sed -i 's/# deb/deb/g' /etc/apt/sources.list &&\
	apt-get install -y --reinstall ca-certificates &&\
	apt-get clean && apt-get update &&\
	apt-get install -y locales language-pack-zh-hans &&\
	localedef -i zh_CN -c -f UTF-8 -A /usr/share/locale/locale.alias zh_CN.UTF-8 && locale-gen zh_CN.UTF-8 &&\
    export DEBIAN_FRONTEND=noninteractive &&\
	apt-get install -y tzdata && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime &&\
	apt-get install -y fontconfig ttf-mscorefonts-installer ttf-wqy-microhei ttf-wqy-zenhei xfonts-wqy
# 安装 arm64-jre8
RUN apt-get install -y openjdk-8-jre

# libreoffice 层
FROM adams549659584/kkfileview-jdk:4.3.0 as kkfileview-jdk
RUN mkdir -p DEBS &&\
    find workdir/installation/ -type f -iname "*.deb" -exec cp {} DEBS/ \;

FROM base-jdk as final

COPY --from=kkfileview-jdk /opt/libreoffice/libreoffice-7-5/DEBS /tmp/DEBS

RUN dpkg -i /tmp/DEBS/*.deb &&\
    #  清理临时文件
	rm -rf /tmp/* && rm -rf /var/lib/apt/lists/* &&\
    cd /usr/share/fonts/chinese &&\
    mkfontscale &&\
    mkfontdir &&\
    fc-cache -fv

# ENV JAVA_HOME /usr/local/jdk1.8.0_251
# ENV CLASSPATH $JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar
# ENV PATH $PATH:$JAVA_HOME/bin
# ENV LANG zh_CN.UTF-8
# ENV LC_ALL zh_CN.UTF-8
CMD ["/bin/bash"]