name: Docker kkFileView CI

on:
  push:
    tags:
      - v*

defaults:
  run:
    shell: bash

jobs:
  mvn-build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

  kkfileview-jdk-docker-build:
    needs: mvn-build
    runs-on: ubuntu-22.04
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to dockerhub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
    
    - name: Build and Push docker image for kkfileview-jdk:${{ github.ref_name }} to dockerhub
      uses: docker/build-push-action@v5
      with:
        context: ./docker/kkfileview-jdk
        file: ./docker/kkfileview-jdk/Dockerfile_arm64
        platforms: linux/arm64
        push: true
        tags: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/kkfileview-jdk:${{ github.ref_name }}
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/kkfileview-jdk:latest
        cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/kkfileview-jdk:cache
        cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/kkfileview-jdk:cache,mode=max

  kkfileview-docker-build:
    needs: kkfileview-jdk-docker-build
    runs-on: ubuntu-22.04
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to dockerhub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
    
    - name: Build and Push docker image for kkfileview:${{ github.ref_name }} to dockerhub
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        platforms: linux/arm64
        push: true
        tags: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/kkfileview:${{ github.ref_name }}
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/kkfileview:latest
        cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/kkfileview:cache
        cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/kkfileview:cache,mode=max

